### ISSUE TITLE
ja-all-enabledブランチのCargoパッケージに全クレート対象のテストケースを追加する

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/atcoder-rust-base#1]
ja-all-enableブランチのCargoパッケージは、AtCoderのジャッジサーバでクレートをビルドするために使用する。

そのパッケージの`tests`ディレクトリ配下にテストケースを追加して、Cargo.tomlの`dependencies`に記述した全てのクレートが使えるかどうか（リンクできるか、バイナリが実行できるか）をテストする。

- [x] proconio
- [x] ordered-float
- [x] modtype 0.4.0
- [ ] modtype 0.6.0 or newer
- [x] ascii
- [x] bitset-fixed
- [x] permutohedron
- [x] superslice
- [x] itertools
- [x] hashbrown
- [x] rustc-hash
- [ ] smallvec
- [ ] arrayvec
- [ ] im, im-rc
- [x] rand, rand_chacha, rand_pcg
- [x] sfmt
- [ ] num
- [x] regex
- [x] lazy_static
- [ ] once_cell
- [x] jemallocator, jemalloc-ctl

**Comment by tatsuya6502** [comment]
本リポジトリをリネームしたため、このissueを新しいリポジトリに作り直した。
https://github.com/rust-lang-ja/atcoder-rust-base/issues/1

**Comment by tatsuya6502** [comment]
ja-all-enabledブランチの以下のファイルにテストケースを追加中。
- [src/main.rs](https://github.com/rust-lang-ja/atcoder-rust-base/blob/ja-all-enabled/src/main.rs)
- [tests/test_jemallocator.rs](https://github.com/rust-lang-ja/atcoder-rust-base/blob/ja-all-enabled/tests/test_jemallocator.rs)

クレートごとの確認状況については、最初のコメントにチェックリストを追加して、そちらで追跡していく。

**Comment by statiolake** [comment]
提案するクレートも多数変更されていますし、新たに #39 もありますので、そちらの方へ移行する形で閉じようと思います。
